# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shai < Formula
  desc "Terminal-native AI agent that turns natural language into shell commands"
  homepage "https://github.com/ameb8/shai"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ameb8/shai/releases/download/v0.2.0/shai_darwin_amd64.tar.gz"
      sha256 "1043ad76a0076aa15422087c08111931e394b6e24111fcca1449ec29d0a275ef"

      define_method(:install) do
        bin.install "_shai_bin"
        (etc/"profile.d").install "shai.sh"
        (etc/"profile.d").install "shai.zsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ameb8/shai/releases/download/v0.2.0/shai_darwin_arm64.tar.gz"
      sha256 "aa89315c91386dbcaff2c5a3b9fe756be02cf259e6ac0dab27f4f1d59d1ec361"

      define_method(:install) do
        bin.install "_shai_bin"
        (etc/"profile.d").install "shai.sh"
        (etc/"profile.d").install "shai.zsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ameb8/shai/releases/download/v0.2.0/shai_linux_amd64.tar.gz"
      sha256 "fb9a9995742ea9799b8877688bbbe7c90dc95b06a1b8f544c7a1de39b587a5fc"
      define_method(:install) do
        bin.install "_shai_bin"
        (etc/"profile.d").install "shai.sh"
        (etc/"profile.d").install "shai.zsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ameb8/shai/releases/download/v0.2.0/shai_linux_arm64.tar.gz"
      sha256 "58c82bc3e41a618d17dea49a561eda30e1af459297d8e3b0e2d365b6c282d37b"
      define_method(:install) do
        bin.install "_shai_bin"
        (etc/"profile.d").install "shai.sh"
        (etc/"profile.d").install "shai.zsh"
      end
    end
  end

  test do
    system "#{bin}/_shai_bin --version"
  end
end
