# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shai < Formula
  desc "Terminal-native AI agent that turns natural language into shell commands"
  homepage "https://github.com/ameb8/shai"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ameb8/shai/releases/download/v0.1.0/shai_darwin_amd64.tar.gz"
      sha256 "0dca1f5519532ce8075d6c016a9b904af0c172dcd970a1b786d1408fffce9d16"

      define_method(:install) do
        bin.install "_shai_bin"
        (etc/"profile.d").install "shai.sh"
        (etc/"profile.d").install "shai.zsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ameb8/shai/releases/download/v0.1.0/shai_darwin_arm64.tar.gz"
      sha256 "bb1547e516d644f1074d85171aa81cef43b0d3c1c7664b6b4dfbc379f8578c1e"

      define_method(:install) do
        bin.install "_shai_bin"
        (etc/"profile.d").install "shai.sh"
        (etc/"profile.d").install "shai.zsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ameb8/shai/releases/download/v0.1.0/shai_linux_amd64.tar.gz"
      sha256 "4f57fa28c837f71552fc82b7fa9036039d529eeedbac47abc20fa35880322b02"
      define_method(:install) do
        bin.install "_shai_bin"
        (etc/"profile.d").install "shai.sh"
        (etc/"profile.d").install "shai.zsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ameb8/shai/releases/download/v0.1.0/shai_linux_arm64.tar.gz"
      sha256 "e2953a791517d081a24c0b32a0d7f096749b92a17ce9fbf32da77df1aa5b1f49"
      define_method(:install) do
        bin.install "_shai_bin"
        (etc/"profile.d").install "shai.sh"
        (etc/"profile.d").install "shai.zsh"
      end
    end
  end

  test do
    system "#{bin}/_shai_bin --version"
  end
end
